"""
scripts/populate_neo4j_json.py

Populate the Neo4j medical graph directly from the JSON files generated by
``scripts/generate_medical_data.py``.  This script avoids the ``LOAD CSV``
approach that fails in the Docker container on Windows due to file‑access
restrictions.

It performs the following steps:
1. Create uniqueness constraints for the main entity labels (Patient, Drug,
   Condition, HealthcareProvider).
2. Load nodes for patients, drugs, conditions, and providers.
3. Create relationships:
   * ``(:Patient)-[:TAKES_DRUG]->(:Drug)``
   * ``(:Patient)-[:HAS_CONDITION]->(:Condition)``
   * ``(:Patient)-[:TREATED_BY]->(:HealthcareProvider)``
   * ``(:Drug)-[:INTERACTS_WITH {severity: ..., mechanism: ...}]->(:Drug)``
   * ``(:Drug)-[:CONTRAINDICATED_FOR]->(:Condition)``

The script is idempotent – it uses ``MERGE`` for nodes and relationships so
re‑running it will not create duplicates.
"""

import sys
import json
from pathlib import Path

# Ensure the repository's ``src`` package is on the import path when this script
# is executed directly (the default working directory is the repository root).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from neo4j import GraphDatabase
from src.config import config

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def load_json(file_name: str) -> list[dict]:
    """Load a JSON file from the repository ``data`` directory.

    Parameters
    ----------
    file_name: str
        Name of the JSON file (e.g. ``patients.json``).

    Returns
    -------
    list[dict]
        Parsed JSON objects.
    """
    path = Path(__file__).parent.parent / "data" / file_name
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def create_constraints(driver):
    """Create uniqueness constraints for core entity labels.

    Neo4j 5+ supports ``IF NOT EXISTS`` on constraints, making this safe to run
    multiple times.
    """
    # Neo4j 5 uses the ``FOR ... REQUIRE`` syntax for constraints.
    constraints = [
        "CREATE CONSTRAINT IF NOT EXISTS FOR (p:Patient) REQUIRE p.patientID IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (d:Drug) REQUIRE d.name IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (c:Condition) REQUIRE c.name IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (hp:HealthcareProvider) REQUIRE hp.name IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (proc:Procedure) REQUIRE proc.name IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (cf:ClinicalFinding) REQUIRE cf.name IS UNIQUE",
    ]
    with driver.session() as session:
        for c in constraints:
            session.run(c)


def load_nodes(driver):
    """Insert Patient, Drug, Condition, and HealthcareProvider nodes.
    """
    patients = load_json("patients.json")
    drugs = load_json("drugs.json")
    conditions = load_json("conditions.json")
    providers = load_json("providers.json")
    procedures = load_json("procedures.json")
    clinical_findings = load_json("clinical_findings.json")

    with driver.session() as session:
        # Patients
        for p in patients:
            session.run(
                "MERGE (p:Patient {patientID: $patientID}) "
                "SET p.name = $name, p.age = $age, p.gender = $gender",
                patientID=p["patientID"], name=p["name"], age=p["age"], gender=p["gender"],
            )
        # Drugs
        for d in drugs:
            session.run(
                "MERGE (d:Drug {name: $name}) SET d.class = $cls",
                name=d["name"], cls=d.get("class", ""),
            )
        # Conditions
        for c in conditions:
            session.run(
                "MERGE (c:Condition {name: $name}) SET c.icd10 = $icd10, c.category = $category",
                name=c["name"], icd10=c.get("icd10", ""), category=c.get("category", ""),
            )
        # Providers
        for hp in providers:
            session.run(
                "MERGE (hp:HealthcareProvider {name: $name}) SET hp.specialty = $specialty",
                name=hp["name"], specialty=hp.get("specialty", ""),
            )
        # Procedures
        for proc in procedures:
            session.run(
                "MERGE (proc:Procedure {name: $name}) SET proc.type = $type",
                name=proc["name"], type=proc.get("type", ""),
            )
        # Clinical Findings
        for cf in clinical_findings:
            session.run(
                "MERGE (cf:ClinicalFinding {name: $name}) SET cf.severity = $severity",
                name=cf["name"], severity=cf.get("severity", ""),
            )


def load_relationships(driver):
    """Create relationships based on the association JSON files.
    """
    patient_drugs = load_json("patient_drugs.json")
    patient_conditions = load_json("patient_conditions.json")
    patient_providers = load_json("patient_providers.json")
    interactions = load_json("interactions.json")
    contraindications = load_json("contraindications.json")
    condition_treatments = load_json("condition_treatments.json")
    patient_procedures = load_json("patient_procedures.json")
    patient_observations = load_json("patient_observations.json")

    with driver.session() as session:
        # Patient -> TAKES_DRUG
        for rel in patient_drugs:
            session.run(
                "MATCH (p:Patient {patientID: $pid}), (d:Drug {name: $dname}) "
                "MERGE (p)-[r:TAKES_DRUG]->(d) "
                "SET r.dosage = $dosage, r.frequency = $freq",
                pid=rel["patientID"], dname=rel["drugName"],
                dosage=rel.get("dosage", ""), freq=rel.get("frequency", ""),
            )
        # Patient -> HAS_CONDITION
        for rel in patient_conditions:
            session.run(
                "MATCH (p:Patient {patientID: $pid}), (c:Condition {name: $cname}) "
                "MERGE (p)-[r:HAS_CONDITION]->(c) "
                "SET r.severity = $severity, r.diagnosisDate = $date",
                pid=rel["patientID"], cname=rel["conditionName"],
                severity=rel.get("severity", 0), date=rel.get("diagnosisDate", ""),
            )
        # Patient -> TREATED_BY
        for rel in patient_providers:
            session.run(
                "MATCH (p:Patient {patientID: $pid}), (hp:HealthcareProvider {name: $hpname}) "
                "MERGE (p)-[:TREATED_BY]->(hp)",
                pid=rel["patientID"], hpname=rel["providerName"],
            )
        # Drug INTERACTS_WITH Drug
        for rel in interactions:
            session.run(
                "MATCH (d1:Drug {name: $d1}), (d2:Drug {name: $d2}) "
                "MERGE (d1)-[r:INTERACTS_WITH]->(d2) "
                "SET r.severity = $severity, r.mechanism = $mechanism",
                d1=rel["drug1"], d2=rel["drug2"],
                severity=rel.get("severity", 0), mechanism=rel.get("mechanism", ""),
            )
        # Drug CONTRAINDICATED_FOR Condition
        for rel in contraindications:
            session.run(
                "MATCH (d:Drug {name: $dname}), (c:Condition {name: $cname}) "
                "MERGE (d)-[:CONTRAINDICATED_FOR]->(c)",
                dname=rel["drug"], cname=rel["condition"],
            )
        # Condition TREATED_BY Drug
        for rel in condition_treatments:
            session.run(
                "MATCH (c:Condition {name: $cname}), (d:Drug {name: $dname}) "
                "MERGE (c)-[:TREATED_BY]->(d)",
                cname=rel["condition"], dname=rel["drug"],
            )
        # Patient UNDERWENT Procedure
        for rel in patient_procedures:
            session.run(
                "MATCH (p:Patient {patientID: $pid}), (proc:Procedure {name: $procname}) "
                "MERGE (p)-[r:UNDERWENT]->(proc) "
                "SET r.date = $date",
                pid=rel["patientID"], procname=rel["procedureName"],
                date=rel.get("date", ""),
            )
        # Patient HAS_OBSERVATION ClinicalFinding
        for rel in patient_observations:
            session.run(
                "MATCH (p:Patient {patientID: $pid}), (cf:ClinicalFinding {name: $cfname}) "
                "MERGE (p)-[r:HAS_OBSERVATION]->(cf) "
                "SET r.date = $date",
                pid=rel["patientID"], cfname=rel["findingName"],
                date=rel.get("date", ""),
            )


def main():
    driver = GraphDatabase.driver(
        config.NEO4J_URI, auth=(config.NEO4J_USER, config.NEO4J_PASSWORD)
    )
    try:
        print("Creating constraints …")
        create_constraints(driver)
        print("Loading nodes …")
        load_nodes(driver)
        print("Loading relationships …")
        load_relationships(driver)
        print("Neo4j population complete.")
    finally:
        driver.close()


if __name__ == "__main__":
    main()
